### ISSUE TITLE
Revise and test conda environment

### ISSUE THREAD

**Issue by bwbush** [NREL/tyche#24]
- [x] Upgrade package versions
- [x] TEST all analysis notebooks with upgraded packages and Python (3.9+)
- [x] TEST running the GUI with upgraded ...
- [x] Remove unused packages
- [x] Test on platforms:
    - [x] Windows (Rebecca and Sam to test)
    - [x] Mac (Caroline and TJ to test)
 - [x] Update documentation: Tyche not supported on Linux

**Comment by rjhanes** [comment]
I did some experimenting with creating conda environments from scratch and from YML files to come up with the new tiny.yml file. In the past we've (I've) had a lot of trouble with creating the completely specified conda environments from a file that had every single package, every dependency, with every version and build number specified. Conda choked on creating these environments *a lot*, especially if any dependencies had changed since the environment file was created.

What I did with tiny.yml is created an environment spec file with a bare minimum number of packages needed by Tyche. When an environment is created from this tiny file, Conda automatically handles identification and installation of the proper dependencies and version. I think, but have not confirmed, that this file should work identically on both Windows and Mac. I have tested a couple analysis notebooks with this updated environment and they are running without error, albeit with a whole bunch of `FutureWarnings` that I'm tracking in another issue.

The command to create a new environment from tiny.yml is:
```
conda env create -f tiny.yml
```

**Comment by rjhanes** [comment]
Update following group testing: The new M1 chip used in Apple can cause issues with Python distributions ([see here for more details](https://towardsdatascience.com/how-to-easily-set-up-python-on-any-m1-mac-5ea885b73fab)) that look like packages not being available and/or package incompatibilities within the environment specification. However, if a Python distribution is set up for the M1 chip before the Tyche conda environment is installed, there should be no issues. We were able to confirm that the minimal environment specification works on both Windows and Apple computers using Intel chips.
